name: 'ESLint Pre-Fix (Windows)'
description: 'Run Python helper to auto-fix ESLint/Prettier issues and emit logs.'
inputs:
  disabled:
    description: 'Disable running pre-fix (1/true to disable)'
    required: false
    default: ''
  strict:
    description: 'Strict mode: fail if fixer returns non-zero (1/true)'
    required: false
    default: ''
outputs:
  logs-dir:
    description: 'Logs directory for this run'
    value: ${{ steps.compute.outputs.dir }}
runs:
  using: 'composite'
  steps:
    - id: compute
      shell: pwsh
      run: |
        $d = Get-Date -Format 'yyyy-MM-dd'
        $p = "logs/$d/eslint"
        New-Item -ItemType Directory -Force -Path $p | Out-Null
        "dir=$p" | Out-File -FilePath $env:GITHUB_OUTPUT -Append -Encoding utf8
        Write-Host "logs dir: $p"
    - id: run
      shell: pwsh
      run: |
        $disabled = ($env:CI_PREFX_DISABLE -eq '1' -or '${{ inputs.disabled }}' -in @('1','true','True','TRUE'))
        if ($disabled) { Write-Host 'ESLint pre-fix disabled'; exit 0 }
        $ErrorActionPreference = 'Continue'
        $code = 0
        $ran = $false
        try {
          & py -3 scripts/python/fix_eslint.py
          $code = $LASTEXITCODE
          $ran = $true
        } catch {
          Write-Warning 'Python launcher (py -3) not found; trying python'
        }
        if (-not $ran) {
          try {
            & python scripts/python/fix_eslint.py
            $code = $LASTEXITCODE
            $ran = $true
          } catch {
            Write-Warning 'python not found; trying python3'
          }
        }
        if (-not $ran) {
          try {
            & python3 scripts/python/fix_eslint.py
            $code = $LASTEXITCODE
            $ran = $true
          } catch {
            Write-Warning 'python3 not found; skipping ESLint pre-fix'
          }
        }
        $strict = ($env:CI_PREFX_STRICT -eq '1' -or '${{ inputs.strict }}' -in @('1','true','True','TRUE'))
        if ($strict -and $code -ne 0) { Write-Error "ESLint pre-fix failed (strict) code=$code"; exit $code }
        exit 0
