name: PR Status Gatekeeper - Windows CI
# Windows CI gatekeeper workflow

on:
  workflow_dispatch:
  pull_request:
    branches: [main, develop]
    types: [opened, synchronize, reopened, ready_for_review]

env:
  GATEKEEPER_TIMEOUT: 5

permissions:
  contents: read
  actions: read
  checks: read

# ==================== Concurrency Control ====================
concurrency:
  group: gatekeeper-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # ==================== Main Gatekeeper Job ====================
  # Primary job for GitHub Actions status check
  windows-ci-gatekeeper:
    name: Windows CI Status Check
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh
    timeout-minutes: 15 # Optimized timeout for 10-minute security gate plus buffer

    # Only run on non-draft PRs
    if: github.event.pull_request.draft == false

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js (for npx availability)
        uses: actions/setup-node@v6.0.0
        with:
          node-version: '22.x'

      - name: Guard JSON BOM (Windows/Python)
        run: npm run guard:bom:json

      - name: Security audit snapshot (npm)
        run: py -3 scripts/ci/run_npm_audit.py

      - name: Upload security audit logs
        if: always()
        uses: actions/upload-artifact@v5
        with:
          name: pr-security-audit-logs
          path: |
            logs/**/security/*.json
          retention-days: 7

      - name: ESLint pre-fix (non-blocking)
        if: runner.os == 'Windows'
        uses: ./.github/actions/eslint-prefx
        continue-on-error: true

      - name: Ensure logs directory exists
        run: |
          New-Item -ItemType Directory -Force -Path "logs/ci" | Out-Null

      - name: Wait for "Unified Security Gate" check
        run: node scripts/ci/wait-for-check.mjs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TARGET_CHECK_NAME: Security Gate (Unified) / Unified Security Gate
          TARGET_JOB_NAME: Unified Security Gate
          TARGET_WORKFLOW_NAME: Security Gate (Unified)
          OPTIONAL: 'true' # Skip if security workflow not triggered (path filters/draft PR etc)
          TIMEOUT_MS: '600000'

      - name: Generate and post PR summary
        run: |
          $summary = @()
          $summary += "## PR Status Summary"
          $summary += "### Windows CI Status"
          $summary += "- **Status**: Windows-focused CI (Build and Test)"
          $summary += "- **Environment**: Windows CI with security gates"
          $summary += ""
          $summary += "### Details"
          $summary += "- **Focus**: Windows-focused CI"
          $summary += "- **Security**: Unified security gate validation"
          $summary += "- **Priority**: P2 - Critical CI validation"
          $summary += "---"
          $summary += "*This gatekeeper ensures Windows CI completion before PR merge*"
          $summary -join "`n" | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append -Encoding utf8

  # ==================== Health Check Job ====================
  workflow-health-check:
    name: Workflow Health Check
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh
    timeout-minutes: 2

    steps:
      - name: Health status report
        run: |
          $summary = @()
          $summary += "## Workflow Health Status"
          $summary += "- **Version**: v1.0"
          $summary += "- **Health Check Time**: UTC"
          $summary += "- **Priority**: P2 - Critical validation"
          $summary -join "`n" | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append -Encoding utf8
