name: tasks-governance

permissions:
  contents: read
  actions: read

defaults:
  run:
    shell: pwsh

# Infrastructure-level optimization: global environment variables
env:
  NODE_VERSION: '22.x'
  CI_RETRY_COUNT: '3'
  CI_TIMEOUT_MINUTES: '15'
  CACHE_STRATEGY: 'aggressive'

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'docs/architecture/overlays/**'
      - 'scripts/overlay-map.json'
      - '.taskmaster/tasks/tasks.json'
      - 'scripts/**'
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate-tasks:
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh
    timeout-minutes: 15

    strategy:
      fail-fast: false
      matrix:
        retry_attempt: [1]

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 1

      - uses: actions/setup-node@v6.0.0
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: |
            package-lock.json
            package.json

      - name: Normalize npm config on Windows
        run: node scripts/ci/npm-normalize-windows.mjs

      - name: Install deps (lean, no native builds)
        uses: ./.github/actions/npm-install
        with:
          mode: lean

      - name: Verify ESLint availability
        run: npx -y eslint --version

      - name: Configure Git line endings (Windows)
        if: startsWith(runner.os, 'Windows')
        run: git config --global core.autocrlf input

      - name: Build overlay map
        run: node scripts/build-overlay-map.mjs

      - name: ensure overlay-map committed
        run: node scripts/ci/ensure-file-unchanged.mjs scripts/overlay-map.json

      - run: node scripts/enrich-tasks.mjs --tasks .taskmaster/tasks/tasks.json --map scripts/overlay-map.json
      - run: node scripts/validate-task-links.mjs --tasks .taskmaster/tasks/tasks.json
